version: 2.1

orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@4.0.1
jobs:
  test:
    executor:
      name: node/default
      tag: "22.14.0"
    steps:
      - checkout
      - node/install-packages
      - run:
          name: "Run Coverage"
          command: npm run coverage
      - run:
          name: "Run Prettier"
          command: npm run prettier:check:ci
      - store_artifacts:
          path: coverage
      - codecov/upload
workflows:
  test:
    jobs:
      - test
