version: 2.1

orbs:
  node: circleci/node@7.1.0
  codecov: codecov/codecov@4.0.1
jobs:
  test:
    executor:
      name: node/default
      tag: "22.14.0"
    steps:
      - checkout
      - run:
          name: "Clean Install"
          command: |
            rm -rf node_modules
            rm -f package-lock.json
            npm install
      - node/install-packages
      - run:
          name: "Run Coverage"
          command: npm run coverage
      - run:
          name: "Run Prettier"
          command: npm run format:check
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: ~/.npm
      - codecov/upload
workflows:
  test:
    jobs:
      - test
